#!/usr/bin/with-contenv bash

pip install -U pip
# Make sure to install setuptools version >=36 to avoid a race condition, see:
# https://github.com/pypa/setuptools/issues/951

if [ ! -z "UPDATE_FLEXGET" ]
then
	fup="-U"
fi
if [ ! -z "UPDATE_PACKAGES" ]
then
	pup="-U"
fi


pip install $pup setuptools>=36
pip install $pup urllib3[socks]
pip install $pup chardet
pip install $pup irc_bot
pip install $pup rarfile
if [ ! -z "$PIP_PACKAGES" ]; then
	pip install $pup $PIP_PACKAGES
fi

# Install flexget last (it might force specific versions of other packages).
pip install $fup flexget
