#!/usr/bin/with-contenv bash

pip install -U pip
# Make sure to install setuptools version >=36 to avoid a race condition, see:
# https://github.com/pypa/setuptools/issues/951
pup=""
fup=""

if [ $PIP_PACKAGES ]; then
	pip install $PIP_PACKAGES
fi

if [ ! -x /usr/bin/flexget ]
then
	pip install setuptools
#	pip install setuptools>=36
	pip install urllib3[socks]
	pip install chardet
	pip install irc_bot
	pip install rarfile
	pip install flexget
else 
	if [ $UPDATE_PACKAGES ]
	then
		echo "Updating pip packages."
		pip install -U setuptools>=36
		pip install -U urllib3[socks]
		pip install -U chardet
		pip install -U irc_bot
		pip install -U rarfile
		if [ ! -z $PIP_PACKAGES ]; then
			pip install -U $PIP_PACKAGES
		fi
	fi
	if [ $UPDATE_FLEXGET ]
	then
		echo "Updating flexget."
		pip install -U flexget
	fi

fi

# Install flexget last (it might force specific versions of other packages).
