#!/bin/bash
if ls /config/*.yml 1> /dev/null 2>&1; then
for i in /config/*.yml 
do
	flexget -c $i database cleanup
	flexget -c $i database vacuum
done
fi
# 'fulfix' for first startup.
chown abc: /config/*
